# Generated by Django 5.1.6 on 2025-02-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image_url_customuser_profile_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='savedpost',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
